### ISSUE TITLE
Picking a grid system/framework/mixin/kijk ff

### ISSUE THREAD

**Issue by FMJansen** [studieverenigingid/i.d-Website#1]
Grids suck everywhere, so we have to find the very best (tududu Pokémon theme song etc.)

**Comment by nwesthoff** [comment]
The way Bootstrap grids work are super intuitive, they have nice (compact) syntax, but Bootstrap's grid system is pretty large @ 10Kb. Pure.css is a lot smaller, but you need to declare your grid size which makes the syntax unnecessarily confusing and large. I haven't found any alternatives that allow to specify a second breakpoint (ex. desktop, tablet and phone) but only allow a single breakpoint (desktop --> phone). Susy is an option as well, but it relies heavily on SASS, which I'm not comfortable with (yet), so I'm not sure how well that would work.
