### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by nwesthoff** [studieverenigingid/i.d-Website#109]
Color doesn't always come through (visible in week 44, maybe on other occasions as well)
happens on [blog](https://studieverenigingid.nl/category/reportid/), maybe other pages as well

Screenshot:
<img width="1680" alt="screenshot 2018-10-30 at 12 00 14" src="https://user-images.githubusercontent.com/7780722/47713786-64601600-dc3b-11e8-970a-93bc4c62a63d.png">

**Comment by FMJansen** [comment]
whooops https://studieverenigingid.nl/honorary_member/will-sneekes/

**Comment by FMJansen** [comment]
Should be fixed with b6459451e8f4a2ad5f01a197bbea2e2534f594d9
