### ISSUE TITLE
Lassie-smoelenboek in WP theme

### ISSUE THREAD

**Issue by FMJansen** [studieverenigingid/i.d-Website#49]

**Comment by nwesthoff** [comment]
Waiting for [search_persons](http://model-docs.lassie.cloud/class-Person_model.html#_search_persons) to be implemented in the Lassie [WordPress](http://docs.moeilijkedingen.nl/display/LD/Wordpress+plugin) plugin.

**Comment by FMJansen** [comment]
Will be solved by #96
