### ISSUE TITLE
Make the website multi-language

### ISSUE THREAD

**Issue by nwesthoff** [studieverenigingid/i.d-Website#59]
- WPML
- PolyLang

**Comment by nwesthoff** [comment]
WPML is almost fully implemented at this point. Strings translation do not work yet. Opened a support thread [here](https://wpml.org/forums/topic/theme-strings-are-found-but-do-not-list-in-string-translations/).

**Comment by FMJansen** [comment]
Already done some time ago by @nwesthoff
